#!/usr/bin/env python3
"""Export a Splatfacto checkpoint to a Gaussian Splat PLY without mesh exporter deps."""

from __future__ import annotations

import argparse
import time
from collections import OrderedDict
from contextlib import contextmanager
from datetime import datetime, timezone
from importlib.metadata import version
from pathlib import Path

import numpy as np
import torch

from nerfstudio.engine.trainer import TrainerConfig
from nerfstudio.models.splatfacto import SplatfactoModel
from nerfstudio.utils.eval_utils import eval_setup
from nerfstudio.utils.rich_utils import CONSOLE


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


@contextmanager
def timed_stage(name: str):
    start = time.perf_counter()
    CONSOLE.print(f"[cyan]{name} started[/cyan] at {utc_now()}")
    try:
        yield
    except Exception:
        elapsed = time.perf_counter() - start
        CONSOLE.print(f"[red]{name} failed[/red] after {elapsed:.2f}s")
        raise
    else:
        elapsed = time.perf_counter() - start
        CONSOLE.print(f"[cyan]{name} finished[/cyan] in {elapsed:.2f}s")


def write_ply(filename: Path, map_to_tensors: OrderedDict[str, np.ndarray]) -> int:
    """Write binary little-endian PLY fields from equally sized numpy arrays."""

    if not map_to_tensors:
        raise ValueError("No tensors were provided")

    count = next(iter(map_to_tensors.values())).size
    arrays: dict[str, np.ndarray] = {}
    dtype_fields: list[tuple[str, str]] = []
    property_types: dict[str, str] = {}

    for key, tensor in map_to_tensors.items():
        arr = np.asarray(tensor)
        if arr.size != count:
            raise ValueError(f"Tensor {key} has {arr.size} values, expected {count}")
        arr = arr.reshape(count)
        if arr.dtype.kind == "f":
            arr = arr.astype(np.float32, copy=False)
            dtype_fields.append((key, "<f4"))
            property_types[key] = "float"
        elif arr.dtype == np.uint8:
            dtype_fields.append((key, "u1"))
            property_types[key] = "uchar"
        else:
            raise ValueError(f"Tensor {key} must be float or uint8, got {arr.dtype}")
        arrays[key] = arr

    structured = np.empty(count, dtype=np.dtype(dtype_fields))
    for key, arr in arrays.items():
        structured[key] = arr

    filename.parent.mkdir(parents=True, exist_ok=True)
    with filename.open("wb") as ply_file:
        nerfstudio_version = version("nerfstudio")
        ply_file.write(b"ply\n")
        ply_file.write(b"format binary_little_endian 1.0\n")
        ply_file.write(f"comment Generated by Nerfstudio {nerfstudio_version}\n".encode())
        ply_file.write(b"comment Vertical Axis: z\n")
        ply_file.write(f"element vertex {count}\n".encode())
        for key in map_to_tensors:
            ply_file.write(f"property {property_types[key]} {key}\n".encode())
        ply_file.write(b"end_header\n")
        structured.tofile(ply_file)

    return count


def build_gaussian_tensors(model: SplatfactoModel, ply_color_mode: str) -> OrderedDict[str, np.ndarray]:
    """Collect Gaussian parameters in the field order expected by common splat tools."""

    map_to_tensors: OrderedDict[str, np.ndarray] = OrderedDict()
    with torch.no_grad():
        positions = model.means.detach().cpu().numpy()
        count = positions.shape[0]

        map_to_tensors["x"] = positions[:, 0]
        map_to_tensors["y"] = positions[:, 1]
        map_to_tensors["z"] = positions[:, 2]
        map_to_tensors["nx"] = np.zeros(count, dtype=np.float32)
        map_to_tensors["ny"] = np.zeros(count, dtype=np.float32)
        map_to_tensors["nz"] = np.zeros(count, dtype=np.float32)

        if ply_color_mode == "rgb":
            colors = torch.clamp(model.colors.clone(), 0.0, 1.0).detach().cpu().numpy()
            colors = (colors * 255).astype(np.uint8)
            map_to_tensors["red"] = colors[:, 0]
            map_to_tensors["green"] = colors[:, 1]
            map_to_tensors["blue"] = colors[:, 2]
        elif ply_color_mode == "sh_coeffs":
            shs_0 = model.shs_0.contiguous().detach().cpu().numpy()
            for i in range(shs_0.shape[1]):
                map_to_tensors[f"f_dc_{i}"] = shs_0[:, i, None]
        else:
            raise ValueError(f"Unsupported color mode: {ply_color_mode}")

        if model.config.sh_degree > 0:
            if ply_color_mode == "rgb":
                CONSOLE.print("Warning: model has SH coefficients; exporting RGB only.")
            else:
                shs_rest = model.shs_rest.transpose(1, 2).contiguous().detach().cpu().numpy()
                shs_rest = shs_rest.reshape((count, -1))
                for i in range(shs_rest.shape[-1]):
                    map_to_tensors[f"f_rest_{i}"] = shs_rest[:, i, None]

        map_to_tensors["opacity"] = model.opacities.detach().cpu().numpy()

        scales = model.scales.detach().cpu().numpy()
        for i in range(3):
            map_to_tensors[f"scale_{i}"] = scales[:, i, None]

        quats = model.quats.detach().cpu().numpy()
        for i in range(4):
            map_to_tensors[f"rot_{i}"] = quats[:, i, None]

    return map_to_tensors


def filter_gaussians(map_to_tensors: OrderedDict[str, np.ndarray]) -> tuple[OrderedDict[str, np.ndarray], int, int]:
    """Drop NaN/Inf rows and gaussians below the opacity threshold used by nerfstudio."""

    count = next(iter(map_to_tensors.values())).size
    select = np.ones(count, dtype=bool)
    nan_or_inf_count = 0

    for key, tensor in map_to_tensors.items():
        finite = np.isfinite(tensor.reshape(count, -1)).all(axis=1)
        invalid = select & ~finite
        invalid_count = int(invalid.sum())
        if invalid_count:
            CONSOLE.print(f"{invalid_count} NaN/Inf elements in {key}")
        nan_or_inf_count += invalid_count
        select &= finite

    low_opacity = map_to_tensors["opacity"].reshape(count) < -5.5373
    low_opacity_count = int((select & low_opacity).sum())
    select &= ~low_opacity

    if int(select.sum()) < count:
        CONSOLE.print(
            f"{nan_or_inf_count} gaussians have NaN/Inf and {low_opacity_count} have low opacity; "
            f"exporting {int(select.sum())}/{count}"
        )
        for key, tensor in map_to_tensors.items():
            map_to_tensors[key] = tensor[select]

    return map_to_tensors, nan_or_inf_count, low_opacity_count


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--load-config", type=Path, required=True, help="Path to a nerfstudio config.yml")
    parser.add_argument("--output-path", type=Path, required=True, help="Path to write the Gaussian Splat PLY")
    parser.add_argument(
        "--ply-color-mode",
        choices=("sh_coeffs", "rgb"),
        default="sh_coeffs",
        help="Export color as spherical harmonics coefficients or RGB fields",
    )
    parser.add_argument(
        "--load-step",
        type=int,
        default=None,
        help="Checkpoint step to load. Defaults to latest checkpoint in the run directory.",
    )
    args = parser.parse_args()

    def update_config(config: TrainerConfig) -> TrainerConfig:
        config.load_step = args.load_step
        return config

    total_start = time.perf_counter()
    CONSOLE.print(f"[bold cyan]Gaussian PLY export started[/bold cyan] at {utc_now()}")
    with timed_stage("checkpoint load"):
        _, pipeline, checkpoint_path, step = eval_setup(
            args.load_config,
            test_mode="inference",
            update_config_callback=update_config,
        )
    if not isinstance(pipeline.model, SplatfactoModel):
        raise TypeError(f"Expected SplatfactoModel, got {type(pipeline.model)}")

    with timed_stage("collect gaussian tensors"):
        tensors = build_gaussian_tensors(pipeline.model, args.ply_color_mode)
    with timed_stage("filter gaussians"):
        tensors, _, _ = filter_gaussians(tensors)
    with timed_stage("write ply"):
        count = write_ply(args.output_path, tensors)
    total_elapsed = time.perf_counter() - total_start
    CONSOLE.print(f"[bold green]Exported {count} gaussians from step {step}[/bold green]")
    CONSOLE.print(f"Checkpoint: {checkpoint_path}")
    CONSOLE.print(f"PLY: {args.output_path}")
    CONSOLE.print(f"[bold cyan]Gaussian PLY export finished[/bold cyan] in {total_elapsed:.2f}s")


if __name__ == "__main__":
    main()
